name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf
  - alabaster
#  - anaconda
#  - anaconda-client
#  - anaconda-navigator
#  - anaconda-project
  - argh
  - asn1crypto
  - astroid
  - astropy
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - backports.shutil_get_terminal_size
  - backports.tempfile
  - backports.weakref
  - bcrypt
  - beautifulsoup4
  - bitarray
  - bkcharts
  - blas
  - bleach
  - blosc
  - bokeh
  - boto
  - bottleneck
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - colorama
#  - comtypes
  - conda
  - conda-build
  - conda-env
  - conda-package-handling
  - conda-verify
  - console_shortcut
  - contextlib2
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - decorator
  - defusedxml
  - diff-match-patch
  - distributed
  - docutils
  - entrypoints
  - et_xmlfile
  - fastcache
  - filelock
  - flake8
  - flask
  - freetype
  - fsspec
  - future
  - get_terminal_size
  - gevent
  - glob2
  - greenlet
  - h5py
  - hdf5
  - heapdict
  - html5lib
  - hypothesis
#  - icc_rt
  - icu
  - idna
  - imageio
  - imagesize
  - importlib_metadata
  - intel-openmp
  - intervaltree
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jdcal
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - keyring
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - libarchive
  - libcurl
  - libiconv
  - liblief
  - libpng
  - libsodium
  - libspatialindex
  - libssh2
  - libtiff
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lxml
  - lz4-c
  - lzo
#  - m2w64-gcc-libgfortran
#  - m2w64-gcc-libs
#  - m2w64-gcc-libs-core
#  - m2w64-gmp
#  - m2w64-libwinpthread-git
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mccabe
#  - menuinst
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mock
  - more-itertools
  - mpmath
  - msgpack-python
#  - msys2-conda-epoch
  - multipledispatch
  - navigator-updater
  - nbconvert
  - nbformat
  - networkx
  - nltk
  - nose
  - notebook
  - numba
  - numexpr
  - numpy
  - numpy-base
  - numpydoc
  - olefile
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - papermill
  - paramiko
  - parso
  - partd
  - path
  - path.py
  - pathlib2
  - pathtools
  - patsy
  - pep8
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkginfo
  - pluggy
  - ply
#  - powershell_shortcut
  - prometheus_client
  - prompt_toolkit
  - psutil
  - psycopg2
  - py
  - py-lief
  - pycodestyle
  - pycosat
  - pycparser
  - pycrypto
  - pycurl
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pynacl
  - pyodbc
  - pyopenssl
  - pyparsing
  - pyqt
#  - pyreadline
  - pyrsistent
  - pysocks
  - pytables
  - pytest
  - pytest-arraydiff
  - pytest-astropy
  - pytest-astropy-header
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - python-dateutil
  - python-jsonrpc-server
  - python-language-server
  - python-levenshtein
  - python-libarchive-c
  - python_abi
  - pytz
  - pywavelets
  - pywin32
#  - pywin32-ctypes
#  - pywinpty
  - pyyaml
  - pyzmq
  - qdarkstyle
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - requests
  - rope
  - rtree
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - snappy
  - snowballstemmer
  - sortedcollections
  - sortedcontainers
  - soupsieve
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - spyder
  - spyder-kernels
  - sqlalchemy
  - sqlite
  - statsmodels
  - sympy
  - tbb
  - tblib
  - terminado
  - testpath
  - tk
  - toolz
  - tornado
  - tqdm
  - traitlets
  - ujson
  - unicodecsv
  - urllib3
#  - vc
#  - vs2015_runtime
  - watchdog
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
#  - win_inet_pton
#  - win_unicode_console
#  - wincertstore
#  - winpty
  - wrapt
  - xlrd
  - xlsxwriter
#  - xlwings
  - xlwt
  - xmltodict
  - xz
  - yaml
  - yapf
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd
  - pip:
    - cx-oracle
    - pyspellchecker
    - oauthenticator
